name: Check Urls

on: [push]

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Download the code
              uses: actions/checkout@v5

            - name: Install Python
              uses: actions/setup-python@v6
              with:
                python-version: "3.12"

            - name: Install the package and pytest
              run: pip install -e ".[dev]"

            - name: Run tests
              run: python -m pytest

            - name: Check URLs
              run: url-status-checker --config checks.yaml
